apiVersion: v1
kind: Service
metadata:
    name: redis-main-service-1
    namespace: default
    labels:
        app: stfs-1
        
spec:
    type: NodePort
    ports:
       - port: 6379
         targetPort: 6379
         nodePort: 30500
    selector:
        app: stfs-1
        name: redis-main-pod
